name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

env:
  FILENAME: deploy.zip
  JAR_NAME: back-0.0.1-SNAPSHOT.jar
  AWS_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  PROJECT_NAME: ${{ secrets.AWS_CODE_DPLOY_APP_NAME }}
  DEPLOY_GROUP_NAME: ${{ secrets.AWS_CODE_DPLOY_GROUP_NAME }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Make Zip File
      run: zip -qq -j ./$FILENAME ./build/libs/$JAR_NAME
      shell: bash

    - name: echo ls
      run: ls -al
      shell: bash

    - name: echo filename
      run: echo $FILENAME
      shell: bash

    - name: Configure AWS Credentials Action for GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-northeast-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$FILENAME s3://$AWS_BUCKET_NAME/$PROJECT_NAME/$FILENAME
#
#    - name: Code Deploy
#      run: aws deploy create-deployment --application-name $PROJECT_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOY_GROUP_NAME --s3-location bucket=$AWS_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$FILENAME
#
